fastlane_version '2.211 '
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
        clean: options[:clean],
        skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
      )
    end
    desc 'beta test'
    lane :beta do
	firebase_app_distribution(
	  app: "1:800117709892:ios:e6122ac6e3d61ff2867011",
	  groups: "Tester",
	  release_notes: "Beta Games"
	)
    end
end
