on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    SwiftLint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: GitHub Action for SwiftLint
          uses: sdiik/action-swiftlint@3.0.1
