name: testing

on:
  pull_request:
    branches:
        - main
jobs:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
       - name: Build
        run: swift build
