name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.ipa
          path: |
            ${{ github.workspace }}/Games.ipa
            ${{ github.workspace }}/*.app.dSYM.zip
            
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: installed versions of Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      
