name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v3
      
      
