name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.ipa
          path: |
            ${{ Games.workspace }}/Games.ipa
            ${{ Games.workspace }}/*.app.dSYM.zip
            
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: installed versions of Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
     
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Swift Packages Cache
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

