name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v3
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      
      
