name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'fix/')
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Game.ipa

      
      
