name: testing

on:
  pull_request:
    branches:
        - main
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'fix/')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup ruby
        uses: actions/setup-ruby@v1
      
      
