name: Fixing

on: issue_comment

jobs:
    pr_comment:
        name: PR comment
        if: ${{ github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
            - run: |
                encho A comment on PR $Number
              env:
                Number: ${{ github.event.issue.number }}
    issue_commented:
        name: Issue comment
        if: ${{ !github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo A comment on issue $NUMBER
              env:
                NUMBER: ${{ github.event.issue.number }}
